#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYSTEMD_USER="${HOME}/.config/systemd/user"
SUNSHINE_OVERRIDE_DIR="${SYSTEMD_USER}/sunshine.service.d"

# ---------------------------------------------------------------------------
# Torna todos os scripts executáveis
# ---------------------------------------------------------------------------
chmod +x \
  "${ROOT}/vmon/sunshine-vmon-common.sh" \
  "${ROOT}/vmon/sunshine-vmon-service.sh" \
  "${ROOT}/vmon/sunshine-vmon-recover.sh" \
  "${ROOT}/vmon/sunshine-start-vmon.sh" \
  "${ROOT}/vmon/sunshine-stop-vmon.sh" \
  "${ROOT}/vmon/sunshine-start-exclusive.sh" \
  "${ROOT}/vmon-simple/sentinel-service.sh" \
  "${ROOT}/vmon-simple/start-desktop.sh" \
  "${ROOT}/vmon-simple/start-exclusive.sh" \
  "${ROOT}/vmon-simple/stop.sh" \
  "${ROOT}/headless/sunshine-labwc-common.sh" \
  "${ROOT}/headless/sunshine-labwc-service.sh" \
  "${ROOT}/headless/sunshine-labwc-recover.sh" \
  "${ROOT}/headless/sunshine-start-labwc.sh" \
  "${ROOT}/headless/sunshine-stop-labwc.sh" \
  "${ROOT}/headless/sunshine-labwc-run.sh" \
  "${ROOT}/headless/sunshine-labwc-input-relay.py" \
  "${ROOT}/headless/sunshine-steam-bigpicture.sh"

mkdir -p "${SYSTEMD_USER}"

# ---------------------------------------------------------------------------
# Escreve os unit files
# ---------------------------------------------------------------------------

# sentinel (vmon-simple)
cat > "${SYSTEMD_USER}/sunshine-sentinel.service" <<EOF
[Unit]
Description=Sunshine sentinel virtual monitor (always connected, never visible)
After=graphical-session.target plasma-workspace.target
Wants=graphical-session.target

[Service]
Type=simple
Environment=XDG_RUNTIME_DIR=/run/user/%U
ExecStartPre=/bin/sleep 12
ExecStart=${ROOT}/vmon-simple/sentinel-service.sh
Restart=on-failure
RestartSec=10
TimeoutStartSec=120

[Install]
WantedBy=default.target
EOF

# vmon (persistente)
cat > "${SYSTEMD_USER}/sunshine-vmon.service" <<EOF
[Unit]
Description=Sunshine virtual monitor (persistent, disabled when idle)
After=graphical-session.target plasma-workspace.target
Wants=graphical-session.target

[Service]
Type=simple
Environment=XDG_RUNTIME_DIR=/run/user/%U
ExecStartPre=/bin/sleep 12
ExecStart=${ROOT}/vmon/sunshine-vmon-service.sh
Restart=on-failure
RestartSec=10
TimeoutStartSec=120

[Install]
WantedBy=default.target
EOF

# labwc (headless)
cat > "${SYSTEMD_USER}/sunshine-labwc.service" <<EOF
[Unit]
Description=Sunshine headless stream compositor (labwc)
After=graphical-session.target
Wants=graphical-session.target

[Service]
Type=simple
Environment=XDG_RUNTIME_DIR=/run/user/%U
ExecStart=${ROOT}/headless/sunshine-labwc-service.sh
Restart=on-failure
RestartSec=5
TimeoutStartSec=60

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload

# ---------------------------------------------------------------------------
# Modo vmon  (vmon-simple e vmon são mutuamente exclusivos)
# ---------------------------------------------------------------------------
echo ""
echo "=== Modo vmon (monitor virtual no KDE) ==="
echo ""
echo "  1) vmon-simple  — monitor criado por stream na resolucao exata do cliente"
echo "                    Servico sentinela garante que Sunshine nao veja 'zero outputs'"
echo "  2) vmon         — monitor persistente criado no login com resolucao fixa"
echo "                    Funciona sem monitor fisico; nao ajusta resolucao por cliente"
echo "  0) nenhum"
echo ""

VMON_OVERRIDE="${SUNSHINE_OVERRIDE_DIR}/vmon-recovery.conf"

vmon_mode=""
case "${SUNSHINE_VMON_MODE:-ask}" in
  simple|1) vmon_mode="simple" ;;
  service|vmon|2) vmon_mode="service" ;;
  0|none|no|false) vmon_mode="none" ;;
  ask|*)
    read -r -p "Modo vmon [1]: " vmon_reply
    case "${vmon_reply:-1}" in
      2|vmon|service) vmon_mode="service" ;;
      0|none|no) vmon_mode="none" ;;
      *) vmon_mode="simple" ;;
    esac
    ;;
esac

case "${vmon_mode}" in
  simple)
    systemctl --user disable --now sunshine-vmon.service 2>/dev/null || true
    systemctl --user enable --now sunshine-sentinel.service
    echo "sunshine-sentinel.service habilitado."

    mkdir -p "${SUNSHINE_OVERRIDE_DIR}"
    cat > "${VMON_OVERRIDE}" <<EOF
# Generated by sunshine-kde-vmon install.sh — vmon-simple crash recovery.
# Remove este arquivo para desabilitar a restauracao automatica do layout.
[Service]
ExecStopPost=${ROOT}/vmon-simple/stop.sh
EOF
    systemctl --user daemon-reload
    echo "Drop-in de recuperacao instalado: ${VMON_OVERRIDE}"
    echo ""
    echo "apps.json: use vmon-simple/start-desktop.sh e vmon-simple/start-exclusive.sh"
    echo "sunshine.conf: capture = kwin  |  output_name = Virtual-sunshine-vmon"
    ;;

  service)
    systemctl --user disable --now sunshine-sentinel.service 2>/dev/null || true
    systemctl --user enable --now sunshine-vmon.service
    echo "sunshine-vmon.service habilitado."

    mkdir -p "${SUNSHINE_OVERRIDE_DIR}"
    cat > "${VMON_OVERRIDE}" <<EOF
# Generated by sunshine-kde-vmon install.sh — vmon crash recovery.
# Remove este arquivo para desabilitar a restauracao automatica do layout.
[Service]
ExecStopPost=${ROOT}/vmon/sunshine-stop-vmon.sh
EOF
    systemctl --user daemon-reload
    echo "Drop-in de recuperacao instalado: ${VMON_OVERRIDE}"
    echo ""
    echo "apps.json: use vmon/sunshine-start-vmon.sh e vmon/sunshine-start-exclusive.sh"
    echo "sunshine.conf: capture = kwin  |  output_name = Virtual-sunshine-vmon"
    ;;

  none)
    systemctl --user disable --now sunshine-vmon.service 2>/dev/null || true
    systemctl --user disable --now sunshine-sentinel.service 2>/dev/null || true
    if [[ -f "${VMON_OVERRIDE}" ]]; then
      rm -f "${VMON_OVERRIDE}"
      systemctl --user daemon-reload
      echo "Drop-in de recuperacao removido."
    fi
    echo "Modo vmon NAO habilitado."
    ;;
esac

# ---------------------------------------------------------------------------
# Modo headless (labwc)
# ---------------------------------------------------------------------------
echo ""
echo "=== Modo headless (compositor labwc isolado) ==="
echo ""
echo "Desktop e apps rodam num compositor Wayland separado; KDE fisico nao e tocado."
echo "Requer: labwc, wlr-randr."
echo "sunshine.conf: capture = wlr  |  output_name = HEADLESS-1"
echo ""

LABWC_OVERRIDE="${SUNSHINE_OVERRIDE_DIR}/labwc-stream.conf"

enable_labwc=false
case "${SUNSHINE_LABWC_ENABLE_SERVICE:-ask}" in
  1|yes|true) enable_labwc=true ;;
  0|no|false) enable_labwc=false ;;
  ask|*)
    read -r -p "Habilitar sunshine-labwc.service? [s/N] " labwc_reply
    [[ "${labwc_reply:-N}" =~ ^[sSyY] ]] && enable_labwc=true || true
    ;;
esac

if [[ "${enable_labwc}" == true ]]; then
  if ! id -nG | grep -qw input; then
    echo "AVISO: usuario '$(id -un)' nao esta no grupo 'input'."
    echo "  O relay de input nao podera capturar dispositivos Sunshine."
    echo "  Para corrigir (requer logout): sudo usermod -aG input $(id -un)"
    echo ""
  fi

  mkdir -p "${SUNSHINE_OVERRIDE_DIR}"
  cat > "${LABWC_OVERRIDE}" <<'OVERRIDE'
# Generated by sunshine-kde-vmon install.sh — labwc stream mode.
# Remove este arquivo para reverter o Sunshine para captura do KDE Plasma.
[Unit]
After=sunshine-labwc.service
Requires=sunshine-labwc.service

[Service]
Environment=WAYLAND_DISPLAY=wayland-stream
OVERRIDE

  systemctl --user daemon-reload
  systemctl --user enable --now sunshine-labwc.service
  echo "sunshine-labwc.service habilitado."
  echo "Drop-in instalado: ${LABWC_OVERRIDE}"
  echo ""
  echo "Passos finais em ~/.config/sunshine/sunshine.conf:"
  echo "  output_name = HEADLESS-1"
  echo "  capture = wlr"
  echo ""
  echo "Reinicie o sunshine.service:"
  echo "  systemctl --user restart sunshine.service"
else
  systemctl --user disable --now sunshine-labwc.service 2>/dev/null || true
  if [[ -f "${LABWC_OVERRIDE}" ]]; then
    rm -f "${LABWC_OVERRIDE}"
    systemctl --user daemon-reload
    echo "Drop-in labwc removido."
  fi
  echo "sunshine-labwc.service instalado mas NAO habilitado."
  echo "Para ativar: SUNSHINE_LABWC_ENABLE_SERVICE=yes ./install.sh"
fi

echo ""
echo "Scripts em: ${ROOT}"
echo "Recuperacao (vmon): ${ROOT}/vmon/sunshine-vmon-recover.sh"
echo "Recuperacao (labwc): ${ROOT}/headless/sunshine-labwc-recover.sh"
