#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYSTEMD_USER="${HOME}/.config/systemd/user"
UNIT="${SYSTEMD_USER}/sunshine-vmon.service"
ENABLE_SERVICE="${SUNSHINE_VMON_ENABLE_SERVICE:-ask}"

chmod +x \
  "${ROOT}/sunshine-vmon-common.sh" \
  "${ROOT}/sunshine-vmon-service.sh" \
  "${ROOT}/sunshine-vmon-recover.sh" \
  "${ROOT}/sunshine-start-vmon.sh" \
  "${ROOT}/sunshine-stop-vmon.sh" \
  "${ROOT}/sunshine-labwc-common.sh" \
  "${ROOT}/sunshine-labwc-service.sh" \
  "${ROOT}/sunshine-labwc-recover.sh" \
  "${ROOT}/sunshine-start-labwc.sh" \
  "${ROOT}/sunshine-stop-labwc.sh" \
  "${ROOT}/sunshine-labwc-run.sh" \
  "${ROOT}/sunshine-labwc-input-relay.py"

mkdir -p "${SYSTEMD_USER}"
cat > "${UNIT}" <<EOF
[Unit]
Description=Sunshine virtual monitor (persistent, disabled when idle)
After=graphical-session.target plasma-workspace.target
Wants=graphical-session.target

[Service]
Type=simple
Environment=WAYLAND_DISPLAY=wayland-0
Environment=XDG_RUNTIME_DIR=/run/user/%U
ExecStartPre=/bin/sleep 12
ExecStart=${ROOT}/sunshine-vmon-service.sh
Restart=on-failure
RestartSec=10
TimeoutStartSec=120

[Install]
WantedBy=default.target
EOF

LABWC_UNIT="${SYSTEMD_USER}/sunshine-labwc.service"
LABWC_OVERRIDE_DIR="${SYSTEMD_USER}/sunshine.service.d"
LABWC_OVERRIDE="${LABWC_OVERRIDE_DIR}/labwc-stream.conf"

cat > "${LABWC_UNIT}" <<EOF
[Unit]
Description=Sunshine headless stream compositor (labwc)
After=graphical-session.target
Wants=graphical-session.target

[Service]
Type=simple
Environment=XDG_RUNTIME_DIR=/run/user/%U
ExecStart=${ROOT}/sunshine-labwc-service.sh
Restart=on-failure
RestartSec=5
TimeoutStartSec=60

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload

# ---------------------------------------------------------------------------
# vmon mode (virtual KDE monitor — existing behaviour)
# ---------------------------------------------------------------------------
do_enable=false
case "${ENABLE_SERVICE}" in
  1|yes|true)
    do_enable=true
    ;;
  0|no|false)
    do_enable=false
    ;;
  ask|*)
    echo ""
    echo "O servico sunshine-vmon roda no login e pode afetar o layout de monitores."
    echo "Versoes anteriores causaram tela preta se o fisico ficou desligado no KDE."
    echo "A versao atual corrige isso, mas teste antes de habilitar no boot."
    echo ""
    read -r -p "Habilitar sunshine-vmon.service agora? [s/N] " reply
    if [[ "${reply}" =~ ^[sSyY] ]]; then
      do_enable=true
    fi
    ;;
esac

if [[ "${do_enable}" == true ]]; then
  systemctl --user enable --now sunshine-vmon.service
  echo "sunshine-vmon.service habilitado."
else
  systemctl --user disable sunshine-vmon.service 2>/dev/null || true
  echo "Servico instalado mas NAO habilitado no boot."
  echo "Para testar manualmente: systemctl --user start sunshine-vmon.service"
fi

# ---------------------------------------------------------------------------
# labwc mode (headless isolated compositor — new behaviour)
# ---------------------------------------------------------------------------
echo ""
echo "=== Modo labwc (compositor isolado / headless stream) ==="
echo ""
echo "Este modo inicia um compositor Wayland separado (labwc) para streaming."
echo "A sessao KDE fisica nunca e tocada. Requer: labwc, wlr-randr."
echo ""
echo "IMPORTANTE: ao habilitar o modo labwc, o Sunshine tambem precisa de"
echo "um override para apontar ao compositor. O instalador pode criar isso."
echo ""

enable_labwc=false
if [[ "${SUNSHINE_LABWC_ENABLE_SERVICE:-ask}" =~ ^(1|yes|true)$ ]]; then
  enable_labwc=true
elif [[ ! "${SUNSHINE_LABWC_ENABLE_SERVICE:-ask}" =~ ^(0|no|false)$ ]]; then
  read -r -p "Habilitar sunshine-labwc.service agora? [s/N] " labwc_reply
  if [[ "${labwc_reply}" =~ ^[sSyY] ]]; then
    enable_labwc=true
  fi
fi

if [[ "${enable_labwc}" == true ]]; then
  # Check input group membership (needed by input relay for mouse/keyboard isolation).
  if ! id -nG | grep -qw input; then
    echo "AVISO: o usuario '$(id -un)' nao esta no grupo 'input'."
    echo "O relay de input NAO podera capturar os dispositivos Sunshine."
    echo "Para corrigir (requer logout apos):"
    echo "  sudo usermod -aG input $(id -un)"
    echo ""
  fi

  # Write sunshine.service drop-in so Sunshine captures from labwc.
  mkdir -p "${LABWC_OVERRIDE_DIR}"
  cat > "${LABWC_OVERRIDE}" <<'OVERRIDE'
# Generated by sunshine-kde-vmon install.sh — labwc stream mode.
# Remove this file to revert Sunshine to capturing from KDE Plasma.
[Unit]
After=sunshine-labwc.service
Requires=sunshine-labwc.service

[Service]
Environment=WAYLAND_DISPLAY=wayland-stream
OVERRIDE

  systemctl --user daemon-reload
  systemctl --user enable --now sunshine-labwc.service
  echo "sunshine-labwc.service habilitado."
  echo "Drop-in instalado em: ${LABWC_OVERRIDE}"
  echo ""
  echo "Passos finais em ~/.config/sunshine/sunshine.conf:"
  echo "  output_name = HEADLESS-1"
  echo "  capture = wlr          # obrigatorio — kwin nao funciona com labwc"
  echo ""
  echo "Reinicie o sunshine.service para completar a configuracao:"
  echo "  systemctl --user restart sunshine.service"
else
  systemctl --user disable sunshine-labwc.service 2>/dev/null || true
  echo "sunshine-labwc.service instalado mas NAO habilitado."
  echo "Para ativar manualmente:"
  echo "  systemctl --user enable --now sunshine-labwc.service"
  echo "  mkdir -p ${LABWC_OVERRIDE_DIR}"
  echo "  cp ${ROOT}/systemd/sunshine-labwc-sunshine-override.conf ${LABWC_OVERRIDE}"
  echo "  systemctl --user daemon-reload"
  echo "  # Em ~/.config/sunshine/sunshine.conf:"
  echo "  #   output_name = HEADLESS-1"
  echo "  #   capture = wlr"
  echo "  systemctl --user restart sunshine.service"
fi

echo ""
echo "Scripts em: ${ROOT}"
echo "Recuperacao (vmon): ${ROOT}/sunshine-vmon-recover.sh"
echo "Recuperacao (labwc): ${ROOT}/sunshine-labwc-recover.sh"
